# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NiceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NiceApp

  target 'NiceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NiceAppUITests' do
    # Pods for testing
  end
  
  pod 'lottie-ios'
end
